import { CardColor } from './types'

export const allColorCombinations: CardColor[][] = [
  [],
  ['U'],
  ['G'],
  ['W'],
  ['R'],
  ['B'],
  ['G', 'U'],
  ['G', 'W'],
  ['B', 'G'],
  ['R', 'W'],
  ['R', 'U'],
  ['B', 'W'],
  ['U', 'W'],
  ['B', 'R'],
  ['G', 'R'],
  ['B', 'U'],
  ['B', 'R', 'U'],
  ['G', 'U', 'W'],
  ['R', 'U', 'W'],
  ['B', 'G', 'R'],
  ['B', 'U', 'W'],
  ['B', 'G', 'U'],
  ['G', 'R', 'U'],
  ['G', 'R', 'W'],
  ['B', 'R', 'W'],
  ['B', 'G', 'W'],
  ['B', 'G', 'U', 'W'],
  ['G', 'R', 'U', 'W'],
  ['B', 'G', 'R', 'W'],
  ['B', 'R', 'U', 'W'],
  ['B', 'G', 'R', 'U'],
  ['B', 'G', 'R', 'U', 'W'],
]
